name:                automata
version:             0.1.0.0
github:              "lsrcz/automata"
license:             BSD3
author:              "Lu Sirui"
maintainer:          "lsrcz@pku.edu.cn"
copyright:           "Copyright (c) 2018 Lu Sirui"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/lsrcz/automata#readme>

dependencies:
- base >= 4.7 && < 5
- unordered-containers
- hashable

library:
  source-dirs: src
  exposed-modules:
    - Data.Automata
    - Data.Automata.DFA
    - Data.Automata.NFA
    - Data.Automata.EpsNFA

tests:
  automata-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - automata
    - hspec
